name: 'Deploy to Payara Cloud'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      PCL_ENDPOINT: ${{ secrets.PCL_ENDPOINT }}
      PCL_CLIENT_ID: ${{ secrets.PCL_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy to Payara Cloud
        uses: payara/cloud-deploy@master
        with:
          token: ${{ secrets.PCL_AUTH_TOKEN }}
          subscription_name: 'you-subscription-name'
          namespace: 'your-namespace-name'
          app_name: 'your-app-name'
          artifact_location: 'your-war-file-location'
          deploy: true